autograd를 알아보자

In [1]:
import torch
from torch.autograd import Variable

x = Variable(torch.ones(2, 2), requires_grad=True)

print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [2]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [3]:
z = y ** 2 * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward1>)


In [4]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


실제로 해볼까?

sum을 알아보자.

In [5]:
a = torch.randn(4, 4, 4)
print(a)

tensor([[[-0.9059,  1.4068,  0.9117, -0.2574],
         [ 0.0230, -0.6518,  0.9007,  0.1131],
         [ 0.3096, -0.6676,  0.0455,  0.9047],
         [-1.2208, -0.3406, -0.4186,  1.2970]],

        [[ 0.8575,  0.1613, -2.0877,  1.4223],
         [-0.6580,  1.1066, -1.7934,  1.6188],
         [ 0.5133, -0.7446, -0.6221, -0.4443],
         [-1.4413, -0.4120, -1.0045,  0.3620]],

        [[ 0.1313,  0.4666,  0.9861, -1.5468],
         [-1.4757, -0.6671,  1.2855,  0.0417],
         [ 1.7318, -0.6868, -0.6767, -0.2551],
         [ 0.8528, -0.5678, -0.0389, -2.8239]],

        [[ 0.2617,  0.5536,  0.0314,  0.3888],
         [-1.0131,  1.1741, -1.1257,  1.1246],
         [-0.3990, -2.2248,  0.8534, -0.4207],
         [ 0.6630, -0.3692, -1.2793,  0.0186]]])


In [6]:
torch.sum(a)

tensor(-6.7225)

dim은 axis이다.

In [7]:
torch.sum(a, 0)

tensor([[ 0.3446,  2.5883, -0.1585,  0.0068],
        [-3.1240,  0.9618, -0.7329,  2.8982],
        [ 2.1557, -4.3238, -0.3999, -0.2155],
        [-1.1463, -1.6896, -2.7413, -1.1463]])

In [8]:
torch.sum(a, 1)

tensor([[-1.7942, -0.2532,  1.4393,  2.0573],
        [-0.7285,  0.1112, -5.5077,  2.9587],
        [ 1.2402, -1.4550,  1.5560, -4.5841],
        [-0.4874, -0.8663, -1.5202,  1.1113]])

In [9]:
torch.sum(a, 2)

tensor([[ 1.1551,  0.3850,  0.5921, -0.6830],
        [ 0.3534,  0.2739, -1.2978, -2.4958],
        [ 0.0372, -0.8156,  0.1133, -2.5777],
        [ 1.2355,  0.1599, -2.1911, -0.9669]])

조금 더 확실히 보자.

In [10]:
torch.sum(a, 0, keepdim=True)

tensor([[[ 0.3446,  2.5883, -0.1585,  0.0068],
         [-3.1240,  0.9618, -0.7329,  2.8982],
         [ 2.1557, -4.3238, -0.3999, -0.2155],
         [-1.1463, -1.6896, -2.7413, -1.1463]]])

In [11]:
torch.sum(a, 1, keepdim=True)

tensor([[[-1.7942, -0.2532,  1.4393,  2.0573]],

        [[-0.7285,  0.1112, -5.5077,  2.9587]],

        [[ 1.2402, -1.4550,  1.5560, -4.5841]],

        [[-0.4874, -0.8663, -1.5202,  1.1113]]])

In [12]:
torch.sum(a, 2, keepdim=True)

tensor([[[ 1.1551],
         [ 0.3850],
         [ 0.5921],
         [-0.6830]],

        [[ 0.3534],
         [ 0.2739],
         [-1.2978],
         [-2.4958]],

        [[ 0.0372],
         [-0.8156],
         [ 0.1133],
         [-2.5777]],

        [[ 1.2355],
         [ 0.1599],
         [-2.1911],
         [-0.9669]]])

view의 활용

In [13]:
x = torch.randn(4, 4)
print(x)

tensor([[ 0.4646, -1.7441,  0.3721, -0.5824],
        [ 0.3402, -1.4459,  1.1414,  0.8484],
        [-0.2230, -1.6352, -0.6418, -0.6083],
        [ 0.9537, -1.8686, -0.1432, -0.0198]])


In [14]:
y = x.view(-1, 2)
print(y)

tensor([[ 0.4646, -1.7441],
        [ 0.3721, -0.5824],
        [ 0.3402, -1.4459],
        [ 1.1414,  0.8484],
        [-0.2230, -1.6352],
        [-0.6418, -0.6083],
        [ 0.9537, -1.8686],
        [-0.1432, -0.0198]])


In [15]:
z = x.view(-1, 4)
print(z)

tensor([[ 0.4646, -1.7441,  0.3721, -0.5824],
        [ 0.3402, -1.4459,  1.1414,  0.8484],
        [-0.2230, -1.6352, -0.6418, -0.6083],
        [ 0.9537, -1.8686, -0.1432, -0.0198]])
